In [1]:
import pandas as pd

In [12]:
df = pd.read_csv("results/experiment_results.csv")

In [13]:
group_cols = ["activation", "optimizer", "structure", "dataset"]
mean_df = df.groupby(group_cols).agg({
    "mse_train": "mean",
    "mse_val": "mean",
    "mse_test": "mean",
    "epochs_run": "mean",
    "fit_time_sec": "mean"
}).reset_index()

mean_df

,activation,optimizer,structure,dataset,mse_train,mse_val,mse_test,epochs_run,fit_time_sec
0,leaky_relu,Adam,"[128, 128, 64]",Dane1_raw,0.227955,0.222854,0.222817,60.1,9.255
1,leaky_relu,Adam,"[128, 128, 64]",Dane1_standardise,0.011992,0.015490,0.006588,108.9,15.747
2,leaky_relu,Adam,"[128, 128, 64]",Dane2_raw,0.000326,0.000305,0.000268,92.3,12.512
3,leaky_relu,Adam,"[128, 128, 64]",Dane2_standardise,0.002984,0.001147,0.002719,79.1,10.280
4,leaky_relu,Adam,"[256, 256, 128]",Dane1_raw,0.141038,0.136265,0.136200,63.9,11.193
...,...,...,...,...,...,...,...,...,...
211,tanh,SGD,[32],Dane2_standardise,0.001321,0.000961,0.000770,117.0,13.521
212,tanh,SGD,"[64, 64, 32]",Dane1_raw,0.027652,0.030940,0.024207,52.5,7.662
213,tanh,SGD,"[64, 64, 32]",Dane1_standardise,0.481450,0.488109,0.472562,16.7,2.879
214,tanh,SGD,"[64, 64, 32]",Dane2_raw,0.011660,0.008886,0.010209,70.4,8.817
215,tanh,SGD,"[64, 64, 32]",Dane2_standardise,0.000919,0.000762,0.000551,89.1,10.958

In [16]:
group_cols = ["activation", "optimizer", "structure", "dataset"]
mean_df = df.groupby(group_cols).agg({
    "mse_train": "mean",
    "mse_val": "mean",
    "mse_test": "mean",
    "epochs_run": "mean",
    "fit_time_sec": "mean"
}).reset_index()

mean_df

,activation,optimizer,structure,dataset,mse_train,mse_val,mse_test,epochs_run,fit_time_sec
0,leaky_relu,Adam,"[128, 128, 64]",Dane1_raw,0.227955,0.222854,0.222817,60.1,9.255
1,leaky_relu,Adam,"[128, 128, 64]",Dane1_standardise,0.011992,0.015490,0.006588,108.9,15.747
2,leaky_relu,Adam,"[128, 128, 64]",Dane2_raw,0.000326,0.000305,0.000268,92.3,12.512
3,leaky_relu,Adam,"[128, 128, 64]",Dane2_standardise,0.002984,0.001147,0.002719,79.1,10.280
4,leaky_relu,Adam,"[256, 256, 128]",Dane1_raw,0.141038,0.136265,0.136200,63.9,11.193
...,...,...,...,...,...,...,...,...,...
211,tanh,SGD,[32],Dane2_standardise,0.001321,0.000961,0.000770,117.0,13.521
212,tanh,SGD,"[64, 64, 32]",Dane1_raw,0.027652,0.030940,0.024207,52.5,7.662
213,tanh,SGD,"[64, 64, 32]",Dane1_standardise,0.481450,0.488109,0.472562,16.7,2.879
214,tanh,SGD,"[64, 64, 32]",Dane2_raw,0.011660,0.008886,0.010209,70.4,8.817
215,tanh,SGD,"[64, 64, 32]",Dane2_standardise,0.000919,0.000762,0.000551,89.1,10.958

In [17]:
group_cols = ["activation", "optimizer", "structure"]
mean_df = df.groupby(group_cols).agg({
    "mse_train": "mean",
    "mse_val": "mean",
    "mse_test": "mean",
    "epochs_run": "mean",
    "fit_time_sec": "mean"
}).reset_index()

mean_df

,activation,optimizer,structure,mse_train,mse_val,mse_test,epochs_run,fit_time_sec
0,leaky_relu,Adam,"[128, 128, 64]",0.060814,0.059949,0.058098,85.100,11.94850
1,leaky_relu,Adam,"[256, 256, 128]",0.040456,0.039345,0.037923,73.125,11.44800
2,leaky_relu,Adam,"[32, 16]",0.228137,0.240973,0.226041,85.450,10.79675
3,leaky_relu,Adam,"[32, 32]",0.221315,0.241319,0.220756,84.475,10.95125
4,leaky_relu,Adam,[32],0.234924,0.248585,0.233063,104.250,12.58850
5,leaky_relu,Adam,"[64, 64, 32]",0.087742,0.082535,0.085029,83.675,11.63925
6,leaky_relu,AdamW,"[128, 128, 64]",0.051413,0.049969,0.048662,91.175,12.62450
7,leaky_relu,AdamW,"[256, 256, 128]",0.014612,0.015257,0.012917,77.625,12.47050
8,leaky_relu,AdamW,"[32, 16]",0.222535,0.233699,0.220127,89.250,11.24500
9,leaky_relu,AdamW,"[32, 32]",0.218805,0.234648,0.217585,77.750,10.19400
10,leaky_relu,AdamW,[32],0.233943,0.252259,0.233108,151.275,17.91925
11,leaky_relu,AdamW,"[64, 64, 32]",0.088225,0.088029,0.085563,82.300,11.51900
12,leaky_relu,SGD,"[128, 128, 64]",0.057771,0.055527,0.056862,86.475,11.39500
13,leaky_relu,SGD,"[256, 256, 128]",0.040629,0.038064,0.040226,84.725,11.98550
14,leaky_relu,SGD,"[32, 16]",0.186137,0.187610,0.183332,74.625,9.32250
15,leaky_relu,SGD,"[32, 32]",0.144145,0.139844,0.141745,75.575,9.57175
16,leaky_relu,SGD,[32],0.232560,0.233860,0.227608,91.000,10.89250
17,leaky_relu,SGD,"[64, 64, 32]",0.094521,0.089469,0.091805,82.100,10.51450
18,relu,Adam,"[128, 128, 64]",0.008092,0.008628,0.005190,88.550,15.41425
19,relu,Adam,"[256, 256, 128]",0.012031,0.012681,0.009900,72.075,14.22600
20,relu,Adam,"[32, 16]",0.166255,0.172167,0.166140,95.400,14.97975
21,relu,Adam,"[32, 32]",0.163574,0.168359,0.162352,95.125,14.16750
22,relu,Adam,[32],0.234033,0.251065,0.232405,127.075,14.89375
23,relu,Adam,"[64, 64, 32]",0.029943,0.028161,0.027413,95.550,16.67975
24,relu,AdamW,"[128, 128, 64]",0.014467,0.013864,0.012346,82.650,11.92175
25,relu,AdamW,"[256, 256, 128]",0.007746,0.008816,0.005251,82.175,12.64725
26,relu,AdamW,"[32, 16]",0.204326,0.208823,0.202255,106.200,13.44525
27,relu,AdamW,"[32, 32]",0.167245,0.171805,0.167114,89.575,11.76625
28,relu,AdamW,[32],0.232565,0.251625,0.231508,126.550,15.07325
29,relu,AdamW,"[64, 64, 32]",0.044960,0.045246,0.041995,98.525,13.78000
30,relu,SGD,"[128, 128, 64]",0.063684,0.062973,0.061998,78.675,10.43875
31,relu,SGD,"[256, 256, 128]",0.045262,0.045198,0.043536,87.125,12.32900
32,relu,SGD,"[32, 16]",0.163438,0.171381,0.162099,91.475,11.48175
33,relu,SGD,"[32, 32]",0.137926,0.139959,0.136318,79.700,10.16575
34,relu,SGD,[32],0.248359,0.267387,0.247877,84.475,10.15800
35,relu,SGD,"[64, 64, 32]",0.048539,0.045509,0.047281,83.475,10.98375
36,tanh,Adam,"[128, 128, 64]",0.129081,0.124521,0.122987,39.175,6.36200
37,tanh,Adam,"[256, 256, 128]",0.126242,0.126084,0.121260,37.150,6.41500
38,tanh,Adam,"[32, 16]",0.180459,0.184345,0.178454,76.575,9.99475
39,tanh,Adam,"[32, 32]",0.186661,0.190299,0.184037,66.900,8.84525
40,tanh,Adam,[32],0.200661,0.211328,0.199027,115.225,13.89450
41,tanh,Adam,"[64, 64, 32]",0.126993,0.121971,0.121067,53.750,8.40725
42,tanh,AdamW,"[128, 128, 64]",0.126005,0.125610,0.121033,37.925,6.02950
43,tanh,AdamW,"[256, 256, 128]",0.125031,0.126163,0.120588,37.975,6.58600
44,tanh,AdamW,"[32, 16]",0.177059,0.184449,0.175920,78.625,10.30925
45,tanh,AdamW,"[32, 32]",0.186799,0.190525,0.184179,66.400,9.18100
46,tanh,AdamW,[32],0.198496,0.211111,0.197310,120.150,14.46525
47,tanh,AdamW,"[64, 64, 32]",0.127986,0.123339,0.122035,53.950,7.92175
48,tanh,SGD,"[128, 128, 64]",0.127758,0.131959,0.124477,54.175,7.43625
49,tanh,SGD,"[256, 256, 128]",0.202117,0.197329,0.195964,46.625,6.67625
50,tanh,SGD,"[32, 16]",0.140653,0.139247,0.138680,104.800,12.93475
51,tanh,SGD,"[32, 32]",0.156625,0.153179,0.153420,64.425,8.63550
52,tanh,SGD,[32],0.195345,0.188969,0.189347,53.100,6.59625
53,tanh,SGD,"[64, 64, 32]",0.130420,0.132174,0.126882,57.175,7.57900

In [15]:
df_no_Dane1_standardise = df[df["dataset"] != "Dane1_standardise"]
group_cols = ["activation"]
mean_df2 = df_no_Dane1_standardise.groupby(group_cols).agg({
    "mse_train": "mean",
    "mse_val": "mean",
    "mse_test": "mean",
    "epochs_run": "mean",
    "fit_time_sec": "mean"
}).reset_index()

mean_df2

   activation  mse_train   mse_val  mse_test  epochs_run  fit_time_sec
0  leaky_relu   0.107377  0.108109  0.105536   94.088889     12.028444
1        relu   0.083899  0.085955  0.082884   98.914815     13.525296
2        tanh   0.051425  0.051337  0.049534   80.281481     10.607981

In [8]:
group_cols = ["optimizer"]
mean_df3 = df.groupby(group_cols).agg({
    "mse_train": "mean",
    "mse_val": "mean",
    "mse_test": "mean",
    "epochs_run": "mean",
    "fit_time_sec": "mean"
}).reset_index()

mean_df3

  optimizer  mse_train   mse_val  mse_test  epochs_run  fit_time_sec
0      Adam   0.135412  0.139573  0.132841   82.145833     11.869556
1     AdamW   0.135679  0.140847  0.133305   86.115278     11.616597
2       SGD   0.134216  0.134424  0.131637   76.651389      9.949819

In [9]:
group_cols = ["structure"]
mean_df4 = df.groupby(group_cols).agg({
    "mse_train": "mean",
    "mse_val": "mean",
    "mse_test": "mean",
    "epochs_run": "mean",
    "fit_time_sec": "mean"
}).reset_index()

mean_df4

         structure  mse_train   mse_val  mse_test  epochs_run  fit_time_sec
0   [128, 128, 64]   0.071009  0.070333  0.067961   71.544444     10.396722
1  [256, 256, 128]   0.068236  0.067660  0.065285   66.511111     10.531500
2         [32, 16]   0.185444  0.191411  0.183672   89.155556     11.612194
3         [32, 32]   0.175899  0.181104  0.174167   77.769444     10.386472
4             [32]   0.223432  0.235132  0.221250  108.122222     12.942361
5     [64, 64, 32]   0.086592  0.084048  0.083230   76.722222     11.002694

In [10]:
group_cols = ["dataset"]
mean_df5 = df.groupby(group_cols).agg({
    "mse_train": "mean",
    "mse_val": "mean",
    "mse_test": "mean",
    "epochs_run": "mean",
    "fit_time_sec": "mean"
}).reset_index()

mean_df5

             dataset  mse_train   mse_val  mse_test  epochs_run  fit_time_sec
0          Dane1_raw   0.234899  0.239863  0.231219   58.081481      9.152407
1  Dane1_standardise   0.297708  0.307725  0.292424   53.264815      8.419574
2          Dane2_raw   0.004793  0.003611  0.004214  117.900000     14.764111
3  Dane2_standardise   0.003009  0.001926  0.002520   97.303704     12.245204

In [11]:
df_no_tanh = df[df["activation"] != "tanh"]
group_cols = ["dataset"]
mean_df6 = df_no_tanh.groupby(group_cols).agg({
    "mse_train": "mean",
    "mse_val": "mean",
    "mse_test": "mean",
    "epochs_run": "mean",
    "fit_time_sec": "mean"
}).reset_index()

mean_df6

             dataset  mse_train   mse_val  mse_test  epochs_run  fit_time_sec
0          Dane1_raw   0.282305  0.288307  0.278643   53.780556      8.708778
1  Dane1_standardise   0.207656  0.220526  0.204418   70.975000     10.955833
2          Dane2_raw   0.000828  0.000542  0.000658  147.994444     18.388889
3  Dane2_standardise   0.003781  0.002246  0.003327   87.730556     11.232944